# ┏━━━┓             ┏┓
# ┃┏━┓┃            ┏┛┗┓
# ┃┗━━┓┏━━┓┏━━┓┏┓┏┓┗┓┏┛
# ┗━━┓┃┃┏┓┃┃┏┓┃┃┃┃┃ ┃┃
# ┃┗━┛┃┃┗┛┃┃┗┛┃┃┗┛┃ ┃┗┓
# ┗━━━┛┃┏━┛┗━━┛┗━━┛ ┗━┛
#      ┃┃
#      ┗┛
#
# Spout Server for Minecraft Java Edition
# 
# Created by Blocks_n_more & Corman

spout:
  motd: "A Spout Server" # The server MOTD when pinging in the server list
  maxplayers: 20 # Maximum users on the server
  port: 25565 # Server port
  hardcore: false # If users have 1 life

  player: # Player specific settings
    gamemode: 0 # Default gamemode
    forcegamemode: true # Set player's gamemode to default on join
    allop: true # Everyone has every permission node

  world:
    generator: "flat" # Built in generators: FLAT, SPOUT

messages: 
  unknowncommand: "Unknown command!"
  missingperms: "You don't have permission to do this!"