import { promises, existsSync } from 'fs';
import { readFile, writeFile } from 'fs/promises';
import logger from '../../utils/logger';

const spout = logger.create('Spout');
const logs = logger.create('EULA');

const getDateStr = () => new Date().toUTCString();

const eulaMessage = `# Generated by Spout
# By changing the setting below to TRUE you are indicating your agreement to mojang's EULA (https://account.mojang.com/documents/minecraft_eula).
# Generated on ${getDateStr()};
# You also agree that pizza is good - Blocks
eula=false`;

const eula = async () => {
    logs.info('Checking EULA...');
    if (!existsSync('./server/eula.txt')) {
        await writeFile('./server/eula.txt', eulaMessage);
        logs.warn('No EULA file found! Creating one.')
    }
    const eulaText = (await readFile('./server/eula.txt'))
        .toString()
        .split(' ')
        .join('');
    if (!(eulaText.toLowerCase().includes('eula=true'))) {
        logs.error(
            'EULA has not been accepted yet! Please accept the eula before continuing!'
        );
        process.exit(1);
    }
    logs.info('EULA Loaded!');
};


export default eula;