"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const promises_1 = require("fs/promises");
const logger_1 = require("../../utils/logger");
const spout = logger_1.default.create('Spout');
const logs = logger_1.default.create('EULA');
const getDateStr = () => new Date().toUTCString();
const eulaMessage = `# Generated by Spout
# By changing the setting below to TRUE you are indicating your agreement to mojang's EULA (https://account.mojang.com/documents/minecraft_eula).
# Generated on ${getDateStr()};
# You also agree that pizza is good - Blocks
eula=false`;
const eula = async () => {
    logs.info('Checking EULA...');
    if (!fs_1.existsSync('./server/eula.txt')) {
        await promises_1.writeFile('./server/eula.txt', eulaMessage);
        logs.warn('No EULA file found! Creating one.');
    }
    const eulaText = (await promises_1.readFile('./server/eula.txt'))
        .toString()
        .split(' ')
        .join('');
    if (!(eulaText.toLowerCase().includes('eula=true'))) {
        logs.error('EULA has not been accepted yet! Please accept the eula before continuing!');
        process.exit(1);
    }
    logs.info('EULA Loaded!');
};
exports.default = eula;
